compile:
	g++ -o RUN_FRONTEND FrontendSystem.cpp Item.cpp User.cpp UserReader.cpp ItemReader.cpp TransactionWriter.cpp TransactionProcessor.cpp main.cpp
compile11:
	g++ -std=c++11 -o RUN_FRONTEND FrontendSystem.cpp Item.cpp User.cpp UserReader.cpp ItemReader.cpp TransactionWriter.cpp TransactionProcessor.cpp main.cpp

clean:
	rm RUN_FRONTEND